In [1]:
import numpy as np #Modül Eklenir

In [2]:
liste=[1,2,3]

In [4]:
array1=np.array(liste)  #Matris Tanımlanır

In [5]:
array1

array([1, 2, 3])

In [6]:
array2=np.array([1,2,3,4,5]) #Diğer Matris Tanımlama

In [8]:
array2

array([1, 2, 3, 4, 5])

In [11]:
array3=np.array([[1,2,3],[4,5,6],[7,8,9]]) #3-3  Matris Tanımlama

In [12]:
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
array4=np.array([1,2,3,4,5,6,7,8,9,10,11,12])  #1-12 Matris Tanımlama

In [15]:
array4=array4.reshape(3,4)  #array4 matrisi 3-4 boyutunda değiştirilir

In [16]:
array4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
array4.shape #Kaça Kaç Matris olduğunu tanımlar

(3, 4)

In [24]:
array3.shape

(3, 3)

In [26]:
array5=np.arange(1,10) #1 den 10'a kadar matris tanımlanır

In [27]:
array5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
array5=np.arange(1,10,2) #1 den 10'a kadar 2 adım ilerleyerek matris tanımlanır

In [30]:
array5

array([1, 3, 5, 7, 9])

In [31]:
array5=np.arange(0,12).reshape(3,4) #0 dan 12'ye kadar 3-4 matris tanımlanır

In [32]:
array5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
array6=np.random.rand(10) #10 tane pozitif ondalıklı rastgele matris üretir

In [36]:
array6

array([0.3879892 , 0.69377832, 0.56559317, 0.14143731, 0.16283161,
       0.69039025, 0.69622318, 0.2596161 , 0.17794636, 0.03102228])

In [46]:
array7=np.random.randn(10) #10 tane pozitif-negatif ondalıklı rastgele matris üretir

In [47]:
array7

array([ 0.61482442,  0.36596502,  0.45983363,  1.62973611, -1.49655476,
       -2.48884066,  0.51346959, -0.23862124,  0.39598317, -1.20776674])

In [63]:
array8=np.random.randint(10) #0 ile 10 arasında sayı üretir

In [64]:
array8

7

In [79]:
array8=np.random.randint(5,10) # 5 ile 10 arasında sayi üretir

In [80]:
array8

9

In [83]:
array8=np.random.randint(0,100,10) # 0 ile 100 arasında 1-10 boyutunda matris üretir

In [84]:
array8

array([97, 14, 18, 83, 28,  5, 57, 85, 89, 35])

In [85]:
array8.resize(5,2)   #Matrisi 5-2 boyutuna dönüştürür

In [86]:
array8

array([[97, 14],
       [18, 83],
       [28,  5],
       [57, 85],
       [89, 35]])

In [88]:
array8.min()         #Matrisin minimum sayısını bulur

5

In [89]:
array8.max()         #Matrisin maximum sayısını bulur

97

In [90]:
array8.sum()         #Matrisin elemanlarını toplar

511

In [93]:
array8.argmin()      #Minimum sayının argümenini verir

5

In [95]:
array8.argmax()      #Maximum sayının argümenini verir

0

In [102]:
np.zeros(10)         #1-10 boyutunda 0 matrisi oluşturur

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [103]:
np.zeros((2,3))     #2-3 boyutunda 0 matrisi oluşturur

array([[0., 0., 0.],
       [0., 0., 0.]])

In [105]:
np.ones(10)         #1-10 boyutunda 1 matrisi oluşturur

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [107]:
np.ones((3,3))     #3-3 boyutunda 1 matrisi oluşturur

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [108]:
np.eye(3)          #3-3 köşegen matris oluşturur

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [111]:
np.diag([2,3,4])  #Belirlenen sayıları köşeye yazar

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [112]:
np.linspace(1,10,5)     #1 ile 10 arasında 5 eşit parçaya böler

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [113]:
array9=np.array([[3,4],[1,2]])

In [114]:
np.linalg.det(array9)   #Array 9'un determinantı alınır

2.0000000000000004

In [10]:
array10=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
array10[0]                         #Matrisin 0. indiksi

array([1, 2, 3])

In [12]:
array10[0][1]                      #Matrisin 0'ın 1.indiksi

2

In [13]:
array10[0][1:]=-1                  #İstenen indiksin değerinin değiştirme

In [14]:
array10

array([[ 1, -1, -1],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [19]:
array10copy=array10.copy()         #Array 10'un kopyası oluşturuluyor

In [20]:
array10copy[0]=[1,1,1]

In [17]:
array10

array([[ 1, -1, -1],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [21]:
array10copy

array([[1, 1, 1],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
array10[1:,0]

array([4, 7])

In [23]:
array10[:,1]

array([-1,  5,  8])

In [24]:
array10t=array10.T              #Matrisin transpozu alınır

In [25]:
array10

array([[ 1, -1, -1],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [26]:
array10t

array([[ 1,  4,  7],
       [-1,  5,  8],
       [-1,  6,  9]])

In [27]:
array11=np.arange(10)

In [28]:
array11

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
array11[array11>3]                 #Koşul sağlayarak matris düzenlenir

array([4, 5, 6, 7, 8, 9])

In [34]:
array12=np.array([0,1,2,3,4])
array13=np.array([5,6,7,8,9])

In [37]:
arraytoplam=array12+array13       #Matrisler Toplanır

In [38]:
arraytoplam

array([ 5,  7,  9, 11, 13])

In [39]:
arraycikarma=array12-array13      #Matrisler Çıkarılır

In [40]:
arraycikarma

array([-5, -5, -5, -5, -5])

In [41]:
array14=np.arange(1,10)

In [42]:
array14.resize(3,3)

In [43]:
array14

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
array14.ndim

2

In [48]:
array14.ravel()      #Matris tek satıra dönüşür

array([1, 2, 3, 4, 5, 6, 7, 8, 9])